---
title: "LINC00667_non_sig_genes_check"
author: "ML"
date: "2024-11_19"
output: html_document
editor_options: 
  chunk_output_type: console
---
#Get genes that filtered out 1795-343=1452
```{r}
LINC00667_non_sig_genes <- LINC00667_trend_sig %>%
  filter(!(gene_name %in% LINC00667_trend_sig_filtered$gene_name))

length(unique(LINC00667_non_sig_genes$gene_name))
#1452
```

#LINC00667 non sig gene TPM plot
```{r}
#for time model
# Load TPM data for LINC00667
tpm_LINC00667 <- read.table("~/Desktop/RNAseq/LINC00667/rowdata/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Load TPM data for LINC00667
tpm_GFP <- read.table("~/Desktop/RNAseq/GFP_12Sept2024/rowdata/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Filter the TPM data for genes in sig_LINC00667_LRT_shrnklfc
filtered_tpm_LINC00667 <- tpm_LINC00667[tpm_LINC00667$gene_name %in% LINC00667_non_sig_genes$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% LINC00667_non_sig_genes$gene_name, ]

# Reshape LINC00667 TPM data to long format
tpm_long_LINC00667 <- filtered_tpm_LINC00667 %>%
  pivot_longer(
    cols = starts_with("LINC00667"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^LINC00667_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "LINC00667"  # Add a column to label as LINC00667
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine LINC00667 and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_LINC00667, tpm_long_GFP)

# Calculate mean and standard error (SE) for TPM at each time point and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(
    mean_tpm = mean(tpm, na.rm = TRUE),
    se_tpm = sd(tpm, na.rm = TRUE) / sqrt(n()),  # Standard error
    .groups = 'drop'
  )

# Plot the combined TPM values for LINC00667 and GFP with error bars
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(aes(color = condition), alpha = 0.5) +  # Points for each mean TPM value
  geom_errorbar(
    aes(ymin = mean_tpm - se_tpm, ymax = mean_tpm + se_tpm, color = condition),
    width = 0.2, # Adjust the width of the error bars
    alpha = 0.7
  ) +
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_color_manual(values = c("LINC00667" = "red", "GFP" = "darkgreen")) +  # Manual color scale
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "~/Desktop/RNAseq/LINC00667/figures/",
  filename = "LINC00667_GFP_non_sig_TPM_individule_v3_with_errorbars.pdf",
  height = 80, width = 120, limitsize = FALSE
)
```

#LINC00667 non sig gene LFC plot
```{r}
# Filter genes from GFP_res_df that are present in LINC00667_trend_sig_filtered
filtered_GFP_res <- GFP_res_df %>%
  filter(gene_id %in% LINC00667_non_sig_genes$gene_id) %>%
  mutate(source = "GFP")

# Add a 0 time_point for GFP data
filtered_GFP_res_zero <- filtered_GFP_res %>%
  dplyr::select(gene_id, gene_name, baseMean) %>%
  distinct() %>%
  mutate(log2FoldChange = 0,
         timepoint = 0,
         source = "GFP")

filtered_GFP_res <- filtered_GFP_res %>%
  bind_rows(filtered_GFP_res_zero)

# Prepare LINC00667 data with source column
LINC00667_non_sig_genes <- LINC00667_non_sig_genes %>%
  mutate(source = "LINC00667")

# Add a 0 time_point for LINC00667
LINC00667_non_sig_genes_zero <- LINC00667_non_sig_genes %>%
  dplyr::select(gene_id, gene_name, baseMean) %>%
  distinct() %>%
  mutate(log2FoldChange = 0,
         timepoint = 0,
         source = "LINC00667")

LINC00667_non_sig_genes <- LINC00667_non_sig_genes %>%
  bind_rows(LINC00667_non_sig_genes_zero)

# Combine LINC00667 and filtered GFP data
combined_data <- bind_rows(LINC00667_non_sig_genes, filtered_GFP_res)

# Generate the plot
ggplot(combined_data, aes(x = timepoint, y = log2FoldChange, group = interaction(gene_id, source), color = source)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_line(alpha = 0.7, aes(linetype = source)) +
  geom_point(alpha = 0.8) +
  facet_wrap(~gene_name, scales = "free_y") +
  scale_color_manual(values = c("LINC00667" = "red", "GFP" = "darkgreen")) +
  scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96")) +
  theme_minimal() +
  labs(title = "Non Sig Gene LFC for LINC00667 and GFP",
       x = "Timepoint (hours)",
       y = "Log2 Fold Change",
       color = "Source",
       linetype = "Source")

# Save the plot
ggsave(path = "~/Desktop/RNAseq/LINC00667/figures/", 
       filename = "LINC00667_vs_GFP_non_sig_lfc_individule.pdf", 
       height = 80, width = 120, limitsize = FALSE)

```

#LINC00667 non sig gene counts plot
```{r}
# Load counts data for LINC00667
counts_LINC00667 <- read.table("~/Desktop/RNAseq/LINC00667/rowdata/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

# Load counts data for LINC00667
counts_GFP <- read.table("~/Desktop/RNAseq/GFP_12Sept2024/rowdata/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

# Filter the counts data for genes in sig_LINC00667_LRT_shrnklfc
filtered_counts_LINC00667 <- counts_LINC00667[counts_LINC00667$gene_name %in% LINC00667_non_sig_genes$gene_name, ]
filtered_counts_GFP <- counts_GFP[counts_GFP$gene_name %in% LINC00667_non_sig_genes$gene_name, ]

# Reshape LINC00667 counts data to long format
counts_long_LINC00667 <- filtered_counts_LINC00667 %>%
  pivot_longer(
    cols = starts_with("LINC00667"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^LINC00667_(\\d+)_(\\d+)$",
    values_to = "counts"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "LINC00667"  # Add a column to label as LINC00667
  )

# Reshape GFP counts data to long format
counts_long_GFP <- filtered_counts_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "counts"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine LINC00667 and GFP data into one data frame
counts_combined_long <- bind_rows(counts_long_LINC00667, counts_long_GFP)

# Calculate mean and standard error (SE) for counts at each time point and condition
counts_mean_combined <- counts_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(
    mean_counts = mean(counts, na.rm = TRUE),
    se_counts = sd(counts, na.rm = TRUE) / sqrt(n()),  # Standard error
    .groups = 'drop'
  )

# Plot the combined counts values for LINC00667 and GFP with error bars
ggplot(counts_mean_combined, aes(x = time_point, y = mean_counts, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(aes(color = condition), alpha = 0.5) +  # Points for each mean counts value
  geom_errorbar(
    aes(ymin = mean_counts - se_counts, ymax = mean_counts + se_counts, color = condition),
    width = 0.2, # Adjust the width of the error bars
    alpha = 0.7
  ) +
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean counts", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_color_manual(values = c("LINC00667" = "red", "GFP" = "darkgreen")) +  # Manual color scale
  scale_x_continuous(breaks = unique(counts_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "~/Desktop/RNAseq/LINC00667/figures/",
  filename = "LINC00667_GFP_non_sig_counts_individule_with_errorbars.pdf",
  height = 80, width = 125, limitsize = FALSE
)
```